#!/usr/bin/env bash
set -euo pipefail
root=$(dirname "$0")

invocation=$1
shift

printf '<!doctype html>
<html>
%s
<body>
  <main>
    %s
  </main>
</body>
</html>
' "$($root/head "$@")" "$($invocation)"
